.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FOR" "1" "January 2016" "" ""
.
.SH "NAME"
\fBfor\fR \- for para minhas man pages v1\.0
.
.SH "NOME"
\fBfor\fR \- for de arquivo MarkDown para gerar Man Pages por Rafael Quirino\.
.
.SH "SYNOPSIS"
\fBfor\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBfor\fR é um documento escrito para facilitar a crição de documentos a partir de um template\. Com a MARCAÇÃO \fImarkup\fR é possível gerar Man Pages usando o comando \fBronn\fR\. Veja mais em ronn(1)\. Necessita Ruby >= 2\.0 com Mustache para funcionar\.\.
.
.SH "OPÇÕES"
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.P
\fB$> for /f %x in (\'some command\') do \.\.\.\fR
.
.P
\fB$> FORFILES /P C:\eWINDOWS /S /M DNS *\.*\fR
.
.P
\fB$> FORFILES /S /M *\.txt /C "cmd /c type @file | more"\fR
.
.P
\fB$> FORFILES /P C:\e /S /M *\.bat\fR
.
.P
\fB$> FORFILES /D \-30 /M *\.exe /C "cmd /c echo @path 0x09 was changed 30 days ago"\fR
.
.P
\fB$> FORFILES /D 01/01/2001 /C "cmd /c echo @fname is new since Jan 1st 2001"\fR
.
.P
\fB$> FORFILES /D +24/7/2013 /C "cmd /c echo @fname is new today"\fR
.
.P
\fB$> FORFILES /M *\.exe /D +1\fR
.
.P
\fB$> FORFILES /S /M *\.doc /C "cmd /c echo @fsize"\fR
.
.P
\fB$> FORFILES /M *\.txt /C "cmd /c if @isdir==FALSE notepad\.exe @file"\fR
.
.SH "ARQUIVOS"
.
.SH "ENVIRONMENT"
.
.SH "DIAGNOSTICS"
.
.SH "COMENTARIOS"
.
.SH "BUGS"
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
help(5), miniman(1), info(1) Windows Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
