.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WMIC" "1" "January 2016" "" ""
.
.SH "NAME"
\fBwmic\fR \- wmic Windows Management Intrumentation Command
.
.SH "NOME"
\fBwmic\fR \- wmic de cliente do WMI que permite executar comandos wmi nos hosts Windows\.
.
.SH "SYNOPSIS"
\fBwmic\fR [\fB/namespace:root\eWMI\fR] [\fBPATH\fR \fICLASS\-NAME\fR ]
.
.SH "DESCRIÇÃO"
\fBwmic\fR é usado para enviar comandos para o sistema operacional via WMI\. É possível recuperar todo tipo de informação do Sistema Operacional, como serial number, hostname, programas instalados, numeros das interfaces de rede, HBA, etc\.
.
.SH "OPÇÕES"
.
.TP
\fB/namespace:\fR
Pode ser usado para indicar o Namespace desejado, no caso /namespace:\eroot\eWMI
.
.TP
\fBPATH CLASS\-NAME\fR
Usado para definir a classe usada para executar o comando que deseja as informações \.
.
.TP
\fBproduct get name\fR
Comando para exibir todos os programas instalados
.
.TP
\fBbios get serialnumber\fR
Exibe o numero serial da máquina\.
.
.SH "EXEMPLOS"
Executar o comando em uma rede inteira 192\.168\.1\.0/24 \fB$> (FOR /L %s IN (1,1,254) DO wmic /node:192\.168\.0\.%s /user:administrator /password:pass bios get serialnumber) >> c:\eresults\.txt\fR \fB$> wmic /node:@nodes\.txt /user:administrator /password:mypassword /output:out\.csv bios get serialnumber /format:csv\fR
.
.P
Executar o comando para um arquivo de servidores\.txt \fB$> (FOR /L %s IN (1,1,254) DO wmic /node:@servidorex\.txt /user:administrator /password:pass bios get serialnumber) >> c:\eresults\.txt\fR
.
.P
Recuperar todos os programas e versão instalados no computador
.
.P
\fB$> wmic product get name,version /format:htable >> x:\e%computername%\.html\fR
.
.P
Recuperar informações sobre as HBA
.
.P
\fB$>wmic /namespace:\e\eroot\eWMI PATH MSFC_FCAdapterHBAAttributes\fR
.
.P
Remover um programa
.
.P
\fB$> product where name="Adobe Reader X" call uninstall\fR
.
.P
Exemplo de como Iniciar e Terminar um processo
.
.P
Exemplo de help para o process
.
.P
\fBwmic:root\ecli process /?\fR
.
.P
Exemplo de uso de parametros
.
.P
\fBwmic:root\ecli PATH SMS_R_System\.LastLogonUserName=\'PTHOMSEN\'\fR
.
.P
Exemplo de uso com PROCESS (Win32_Process) / Starting and Exiting
.
.P
`
.
.P
$> WMIC PROCESS CALL Create "calc\.exe"
.
.P
$> WMIC PROCESS WHERE Name="calc\.exe" CALL Terminate
.
.P
$> WMIC PROCESS WHERE Name="explorer\.exe" call SetPriority 64
.
.P
Identico a:
.
.P
$> WMIC PATH Win32_Process WHERE Name="explorer\.exe" call SetPriority 64
.
.P
2\.0 Data display:
.
.P
WMIC PROCESS WHERE "name like \'%HOST%\'"
.
.P
WMIC PATH Win32_Process WHERE "name like \'%HOST%\'"
.
.P
WMIC PROCESS WHERE “Name=svchost\.exe” LIST Statistics
.
.P
WMIC PROCESS WHERE “Name=svchost\.exe” LIST BrieF
.
.P
WMIC PROCESS WHERE (Name=\'svchost\.exe\') GET name, processid
.
.P
WMIC PROCESS WHERE “Name=svchost\.exe” GET name,processid /VALUE
.
.P
WMIC PROCESS GET /FORMAT:htable
.
.P
WMIC PROCESS GET /FORMAT:”c:\ewindows\esystem32\ewbem\ehtable\.xsl”
.
.P
WMIC PROCESS GET /FORMAT:hform
.
.P
WMIC PROCESS GET /FORMAT:csv
.
.P
4\.0 Data output:
.
.P
WMIC BIOS > mydata\.txt
.
.P
WMIC OS >> mydata\.txt
.
.P
WMIC /APPEND:mydata\.txt PAGEFILE
.
.P
WMIC /OUTPUT:output\.txt OS
.
.P
WMIC /OUTPUT:CLIPBOARD BIOS
.
.P
3\.0 Data creation:
.
.P
WMIC /NAMESPACE:\eroot\edefault PATH __Namespace CREATE Name=test
.
.P
4\.0 Data deletion:
.
.P
WMIC /NAMESPACE:\eroot\edefault PATH __Namespace WHERE Name="test" DELETE
.
.P
WMIC /NAMESPACE:\eroot\esubscription PATH \fBEventFilter WHERE\fRCLASS="__EventFilter" DELETE
.
.P
5\.0 Security and connection:
.
.P
Delegate authority
.
.P
WMIC /node:"computer1" /IMPLEVEL:Delegate /AUTHORITY:"Kerberos:domain\ecomputer1" OS
.
.P
WMIC /NODE:"computer1\.domainofcomputer1\.org" /AUTHLEVEL:Pktprivacy BIOS
.
.P
6\.0 Batch scripting:
.
.P
WMIC\.EXE /OUTPUT:WMICLASSES\.txt /NAMESPACE:\eroot\ewmi PATH WDMClassesOfDriver GET Classname
.
.P
for /f "usebackq skip=1" %%I in (\fBtype WMICLASSES\.txt\fR) DO WMIC\.exe /namespace:\eroot\ewmi PATH %%I
.
.P
WMIC PROCESS GET /FORMAT:"%windir%\esystem32\ewbem\ecsv\.xsl" >> c:\e1\.csv
.
.P
`
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
wmic(5), powershell(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
