.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ARPSPOOF" "1" "October 2016" "" ""
.
.SH "NAME"
\fBarpspoof\fR \- arpspoof Forjador de pacotes ARP
.
.SH "NOME"
\fBarpspoof\fR \- Fazer spoof de pacotes ARP na rede local\.
.
.SH "SYNOPSIS"
\fBarpspoof\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBarpspoof\fR é utilizado para realizar o spoof de pacotes ARP, que só pode ser realizado dentro de uma rede local\. Dessa forma o atacante envia pacotes de resposta ao IP solicitado com seu MAC ADDRESS, recebendo todo o tráfego do alvo\.
.
.SH "OPÇÕES"
arpspoof \-i \fIINTERFACE\fR \-t \fIIP_DO_ALVO\fR \fIIP_QUE_SEU_ALVO_VAI_MAPEAR_PARA_SEU_MAC\fR
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.P
\fB$> date \'%Y/%m/%d\'\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
