.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BMON" "1" "December 2016" "" ""
.
.SH "NAME"
\fBbmon\fR \- usado para monitorar o consumo de banda nas interfaces de rede\.
.
.SH "SYNOPSIS"
\fBbmon\fR [\fBOPCAO\fR]
.
.SH "DESCRIÇÃO"
\fBbmon\fR é usado para exibir o tráfego de rede de forma grafica separada e intuitiva, um dos melhores programas que já vi para isso\.
.
.SH "OPÇÕES"
.
.TP
\fB\-o\fR \fIncurses:graph=2\fR
Exibe usando 2 graficos, interessante essa funcao\.
.
.TP
\fB\-i\fR interval
Exibe com intervalo de X segungos\.
.
.SH "EXEMPLOS"
Listar os modulos disponiveis\.
.
.P
\fB$> bmon \-o list\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
