.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "COMPLETE" "1" "December 2016" "" ""
.
.SH "NAME"
\fBcomplete\fR \- completeo para minhas man pages v1\.0
.
.SH "NOME"
\fBcomplete\fR \- Mostra o bash_completion
.
.SH "SYNOPSIS"
\fBcomplete\fR [\fBoptions\fR ] [OPTIONS]
.
.SH "DESCRIÇÃO"
\fBcomplete\fR \- Mostra o bash_completion que é usado para completar o \fITAB\fR \fITAB\fR
.
.SH "OPÇÕES"
.
.TP
\fB\-p\fR
\fIprint\fR Mostra o bash_completion default
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.P
`$> complete \-p | less
.
.SH "ARQUIVOS"
*/etc/bash_completion Arquivo de configuração de sistema do completar \fITAB\fR\fITAB\fR do bash\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
