.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DATE" "1" "June 2018" "" ""
.
.SH "NAME"
\fBdate\fR \- Manipular datas
.
.SH "SYNOPSIS"
\fBdate\fR [\fB\-conta de tempo\fR] [` \fIOPCOES\fR ]
.
.SH "DESCRIÇÃO"
\fBdate\fR Usado para exibir a data e hora de acordo com os parametros, seguem os mais utilizados\.
.
.SH "OPÇÕES"
.
.TP
\fB%d\fR
Exibe o dia como numero, ex: 23
.
.TP
\fB%m\fR
Exibe o mes como numero, ex: 12
.
.TP
\fB%Y\fR
Exibe o dia como numero, ex: 2016
.
.TP
\fB%y\fR
Exibe o ano como numero, ex: 16
.
.TP
\fB%s\fR
Exibe o TIMESTAMP, numero de segundos passados depois de 1970\.
.
.SH "EXEMPLOS"
Exemplos de data:
.
.P
\fB$> date +%d\-%m\-%Y\fR 14\-03\-2017
.
.P
\fB$> date +\'%B\'\fR March
.
.P
\fB$> date +%D\fR 03/14/17
.
.P
Returns the real date from epoch time: date –d @1284127201
.
.P
Return an epoch time of 1288756800: date +%s \-d “2010\-11\-03”
.
.P
Return a 2 days old date: date \-\-date="\-2 days" +"%Y\-%m\-%d"
.
.P
Return 20:00 hours: date \-d @1288310401 +%k:%M
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
