.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DIG" "1" "March 2017" "" ""
.
.SH "NAME"
\fBdig\fR \- dig \- usado para questionar o DNS Server
.
.SH "SYNOPSIS"
\fBdig\fR [\fBTIPO\fR] [\fIhostname\fR] @\fI\fIIP\-DNSSERVER\fR\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBdig\fR é usado para fazer querys simples e complexas para o servidor de DNS\.
.
.SH "OPÇÕES"
.
.TP
\fBMX\fR
Faz querys para saber que é o MaileXchanger do Domínio informado\.
.
.TP
\fBafxr\fR
Solicita a transferencia de Zonas da Domínio para mim(host)\.
.
.TP
\fBifxr\fR
Solicita a transferência incremental, ou seja traz somente oque foi alterado\.
.
.TP
\fBNS\fR
Faz querys para saber que é
.
.TP
\fBPTR\fR
Faz querys somente para consultar os IPS e devolver os nomes, ou seja REVERSO\.
.
.TP
\fBDEBUG\fR
Serve para exibir tudo\.
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.P
\fB$> date \'%Y/%m/%d\'\fR
.
.P
\fITeste de SPF\fR
.
.P
\fB$> dig TXT uol\.com\.br +short\fR \fB$> dig TXT _net1\.uol\.com\.br +short\fR \fB$> dig TXT _net2\.uol\.com\.br +short\fR
.
.SH "ARQUIVOS"
\fI/etc/resolv\.conf\fR Arquivo para configuração de resolvedor de nomes Locais para *n?x like\.
.
.SH "ENVIRONMENT"
\fBnslookup\fR Também pode ser usado para enviar QUERIES para servidores de DNS\.
.
.SH "DIAGNOSTICS"
Usando o nslookup é possível fazer um diagnótico mais detalhado\.
.
.P
\fBset debug\.\fR Configura o format de debug para uso do nslookup
.
.P
**set query={A,TXT,PTR,NS,MX} \fBA\fR configura modo de retorno de QUERIES somente para tipo A\. \fBTXT\fR configura modo de retorno de QUERIES somente para tipo TXT\. \fBPTR\fR configura modo de retorno de QUERIES somente para tipo REVERSO\. \fBNS\fR configura modo de retorno de QUERIES somente para tipo NS(Domain servers)\. \fBMX\fR configura modo de retorno de QUERIES somente para tipo MX(Mail eXchange)\.
.
.SH "COMENTARIOS"
Coloque seus comentários aqui\.\.\. <\- Tag para comentários na Man Page, juro, não sai nada\.>
.
.SH "BUGS"
The command name should have been chosen more carefully to reflect its purpose\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
