.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EXPECT" "1" "March 2017" "" ""
.
.SH "NAME"
\fBexpect\fR \- Script para interagir com sistemas\.
.
.SH "SYNOPSIS"
\fBexpect\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBexpect\fR é uma lingaguem de programação para intereagir com sistemas\.
.
.SH "OPÇÕES"
.
.TP
\fB\-d\fR
Modo debug
.
.SH "EXEMPLOS"
\fILendo argumentos\fR set arg1 [lindex $argv 0]
.
.P
puts => printf
.
.P
set timeout => define um tempo para o expect aguardar\.
.
.P
spawn comando paramtros => executa o comando com seus parametros\.
.
.P
set fd1[open "~/arquivo\.txt"] set senha1 [read $fd1] => Le o arquivo arquivo\.txt e coloca o conteudo em senha1
.
.P
expect \-exact "ssh aspen\er => Espera exatamente "ssh aspen"
.
.SH "ENVIRONMENT"
\fBTCL\fR Expect por padrão usa as mesma nuances e caracteristicas de TCL, miniman tcl para mais informações\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
