.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GDB" "1" "March 2017" "" ""
.
.SH "NAME"
\fBgdb\fR \- GNU Debugger
.
.SH "SYNOPSIS"
\fBgdb\fR [\fB\-opcoes\fR] [\fB\-c\fR \fIcore\-dump\fR ] \fIbinario\fR roff: \./gdb\.1
.
.SH "DESCRIÇÃO"
\fBgdb\fR Usado para debugar problemas no binário e fazer engenharia reversa\.
.
.SH "OPÇÕES"
.
.TP
\fB\-c\fR \fIcore\-dump\fR
Analisa o arquivo core dump gerado pelo erro da execução da aplicação\.
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.P
\fB$> gdb \./binario \-c core\-dump\'\fR
.
.SH "ARQUIVOS"
\fI/var/log/core\-dump\fR Pasta no sistema onde ficam os arquivos de core\-dump, pode mudar de sistema para sistema\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
