.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GEM" "1" "March 2017" "" ""
.
.SH "NAME"
\fBgem\fR \- Ruby instalador
.
.SH "SYNOPSIS"
\fBgem\fR [\fBinstall\fR] [\fInome\-do\-pacote\fR ]
.
.SH "DESCRIÇÃO"
\fBgem\fR Usando para instalar e fazer todo o gerenciamento de pacotes Ruby\.
.
.SH "OPÇÕES"
.
.TP
\fB\-\-proxy <PROXY_IP>\fR
Usado para informar um servidor PROXY para conexão a internet\.
.
.SH "EXEMPLOS"
Informando um servidor de proxy HTTP para acessar a internet\.
.
.P
\fB$> gem install \-\-http\-proxy http://localhost:8888 $gem_name\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
