.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ICONV" "1" "October 2016" "" ""
.
.SH "NAME"
\fBiconv\fR \- Conversor de arquivos
.
.SH "NOME"
\fBiconv\fR \- programa de conversão de codificação de texto\.
.
.SH "SYNOPSIS"
\fBiconv\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIarquivo\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBiconv\fR é um programa para converter codificação de arquivos, exemplo UTF\-8 ISO\-8859\-1 Western bla bla bla\.\.\.
.
.SH "OPÇÕES"
.
.IP "\(bu" 4
\fB\-f\fR \fIfile\-encode\fR: (from) Define tipo do arquivo de origem\. \-> utf\-8 , iso\-8859\-1
.
.IP "\(bu" 4
\fB\-t\fR \fIfile\-encode\fR: (to) Define o tipo que será converido \-> utf\-8 , iso\-8859\-1
.
.IP "\(bu" 4
\fB\-c\fR \fIfile\-name\fR
.
.IP "" 0
.
.SH "EXEMPLOS"
.
.IP "\(bu" 4
converte o arquivo\.txt para UTF\-8
.
.IP
\fB$> iconv \-f utf\-8 \-t ucs\-4 < arquivo\.txt >/dev/null\fR
.
.IP "\(bu" 4
limpa os caracteres estranhos no arquivo
.
.IP
\fB$> iconv \-f utf\-8 \-t utf\-8 \-c file\.txt > novoarquivo\-limpo\.txt\fR
.
.IP "" 0
.
.SH "ARQUIVOS"
\fIarquivo\.txt\fR O arquivo utilizado como entrnada\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
