.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "IF" "1" "August 2015" "" ""
.
.SH "NAME"
\fBif\fR \- testa e executada alguma função
.
.SH "NOME"
if \- realiza um teste e pode executar algo caso verdade ou falso\.
.
.SH "SYNOPSIS"
\fBif\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBif\fR é uma ferramenta do shell para teste de condições, em caso de verdadeiro ele executa alguma função\.
.
.SH "OPÇÕES"
.
.IP "\(bu" 4
\fB\-n\fR: Non\-zero \-> Teste se náo for nulo, veja se a var contém algo pelo menos\. q
.
.IP "\(bu" 4
\fB\-z\fR: Verifica se a variável foi setada, pode até ser vazia\.
.
.IP "\(bu" 4
\fB\-e\fR: Verifica se o \fIarquivo\fR existe\.
.
.IP "\(bu" 4
\fB\-d\fR: Verifica se o diretório existe\.
.
.IP "\(bu" 4
\fB\-eq\fR: igual
.
.IP "\(bu" 4
\fB\-ne\fR: diferente
.
.IP "\(bu" 4
\fB\-gt\fR: maior
.
.IP "\(bu" 4
\fB\-ge\fR: maior ou igual
.
.IP "\(bu" 4
\fB\-lt\fR: menor
.
.IP "\(bu" 4
\fB\-le\fR: menor ou igual
.
.IP "\(bu" 4
\fB\-d\fR: se é um diretório
.
.IP "\(bu" 4
\fB\-e\fR: se existe
.
.IP "\(bu" 4
\fB\-z\fR: se é vazio
.
.IP "\(bu" 4
\fB\-f\fR: se contem texto\.
.
.IP "\(bu" 4
\fB\-r\fR: se o arquivo possui permissão de leitura
.
.IP "\(bu" 4
\fB\-w\fR: se o arquivo possui permissão de escrita\.
.
.IP "\(bu" 4
\fB\-x\fR: se o arquivo é executavel\.
.
.IP "" 0
.
.SH "EXAMPLES"
Comparando uma variável se está vazia\.
.
.IP "" 4
.
.nf

`if [ \-n $USER ]; then

    echo "Sou o:$USER"
else
    echo "Não sou ninguém"
fi`

   `if [ \-z "$1" ]                           # Is parameter #1 zero length?
.
.fi
.
.IP "" 0
.
.P
`then echo "\-Parameter #1 is zero length\.\-" # Or no parameter passed\. else echo "\-Parameter #1 is \e"$1\e"\.\-" fi
.
.P
variable=${1\-$DEFAULT} # What does echo "variable = $variable" #+ parameter substitution show? # \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- # It distinguishes between #+ no param and a null param\.`
.
.P
\fBif [ "$2" ] then echo "\-Parameter #2 is \e"$2\e"\.\-" fi\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
