.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ISCSIADM" "1" "September 2015" "" ""
.
.SH "NAME"
\fBiscsiadm\fR \- iscsiadm iSCSI Admin
.
.SH "NOME"
\fBiscsiadm\fR \- iscsiadm é um cliente para acesso e mapeamento de discos iSCSI\.\.
.
.SH "SYNOPSIS"
\fBiscsiadm\fR [\fB\-m MODE\fR] [\fB\-p\fR \fIip\fR ] \fIiface\fR
.
.SH "DESCRIÇÃO"
\fBiscsiadm\fR é um documento escrito para facilitar a crição de documentos a partir de um template\. Com a MARCAÇÃO \fImarkup\fR é possível gerar Man Pages usando o comando \fBronn\fR\. Veja mais em ronn(1)\. Necessita Ruby >= 2\.0 com Mustache para funcionar\.\.
.
.SH "OPÇÕES"
.
.TP
MODE:

.
.TP
\fBdiscovery\fR
Usado para descobrir(MOSTRAR) os targets iqn, ja encontrados\.
.
.TP
\fBnode\fR
Usado para se tornar ou nao um no que usa o Target IQN ou nao usa\.
.
.TP
OPCOES:

.
.TP
\fB\-t st\fR
Usado para enviar do SENDTARGETS, para descobrir as informacoes do STORAGE\.
.
.TP
\fB\-p\fR
IP do PORTAL do Storage ou o servidor de ISCSI\.
.
.TP
\fB\-\-portal <IP>\fR
Usado para indicar o endereço IP do servidor que tem o Portal para conexão\.
.
.TP
\fB\-\-login\fR
Usado para fazer o login no target iSCSI, basta mandar um fdisk \-l para ver o disco já entregue para o SO\.
.
.TP
\fB\-\-logout\fR
Usado para fazer o logout no target iSCSI, dessa forma o disco é removido do SO\.
.
.TP
\fB\-\-targetname <IQN>\fR
Usado para indicar o nome do target IQN a ser utilizado, use o modo de discovery unido a opção de
.
.TP
\fB\-o delete \-p PORTAL:3260\fR
Apagar um target portal
.
.SH "EXEMPLOS"
Para descobrir os targets IQN que existem para determinado portal:
.
.P
\fB$> iscsiadm \-m discovery \-t st \-p 192\.168\.45\.145\fR
.
.P
O retorno é algo parecido com isso:
.
.P
192\.168\.45\.145:3260,1 iqn\.2006\-01\.com\.openfiler:tsn\.73ef1a2e5abf 192\.168\.45\.145:3260,1 iqn\.2006\-01\.com\.openfiler:tsn\.acc51ecccc11
.
.P
Para logar em um target e poder usa\-lo\.
.
.IP "" 4
.
.nf

`$> iscsiadm \-m node \-\-targetname "iqn\.2007\-09\.com\.google\.www:disk0" \-\-portal "192\.168\.1\.250:3260" \-\-login `
.
.fi
.
.IP "" 0
.
.P
o retorno é algo parecido com isso:\fBLogging in to [iface: default, target: iqn\.2007\-09\.com\.google\.www:disk0, portal: 192\.168\.1\.250,3260] (multiple) Login to [iface: default, target: iqn\.2007\-09\.com\.google\.www:disk0, portal: 192\.168\.1\.250,3260] successful\.\fR
.
.P
Para deslogar para mandar o logout no final \fB$> iscsiadm \-m node \-\-targetname "iqn\.2007\-09\.com\.google\.www:disk0" \-\-portal "192\.168\.1\.250:3260" \-\-logout\fR
.
.P
Apagar um Portal ja cadastrado: \fB$> iscsiadm \-m discovery \-o delete \-p 192\.168\.1\.30:3260\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
iscsid(1), iscsi\-utils(1), Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
