.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LINGUEMCTL" "1" "September 2017" "" ""
.
.SH "NAME"
\fBlinguemctl\fR \- Sistema de Email proprietário\.
.
.SH "SYNOPSIS"
\fBlinguemctl\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBlinguemctl\fR é um servidor de email\.
.
.SH "OPÇÕES"
Listar os usuários com status\. * \fBlinguemctl hs check \-\-detail all\fR:
.
.P
Use the alternate system wide \fIconfig\-file\fR instead of \fI/etc/foo\.conf\fR\. This overrides any \fBFOOCONF\fR environment variable\. * \fBlinguemctl us status alexandre@qualisegco\.dominiotemporario\.com\fR
.
.P
Exibir todas as versões dos HS\. * \fBlinguemctl hs version all\fR:
.
.P
Listar a situação dos File Servers do Linguem, filtrando por nitro52\. * \fBlinguemctl fs list | grep nitro52\fR:
.
.P
Listar \fIinfos do HS emerge192\fR: \fBlinguemctl hs info emerge192\fR:
.
.P
\fBHS\fR
.
.P
\fISuspender HS\fR: \fBlinguemctl hs status suspended <HS_NAME>\fR
.
.P
\fIDes Suspender:\fR \fBlinguemctl hs status up <HS_NAME>\fR
.
.P
\fISlow HS\fR: \fBlinguemctl hs status slow <HS_NAME>\fR
.
.P
\fIListar Versao dos HS´s\fR \fBlinguemctl hs version all\fR \fBlinguemctl hs version <HS_NAME>\fR
.
.P
\fBUSUARIO\fR
.
.P
\fIStatus do usuário/email\fR \fBlinguemctl user status <EMAIL@bol\.com\.br/sem uol\.com\.br>\fR
.
.P
\fIReplicar Usuários:\fR \fBlinguemctl hs replicate \-\-topusers 2000 emerge113\-a\fR
.
.SH "EXEMPLOS"
Suspender HS \fB$> lc hs status suspended <HS_NAME>\'\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
