.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LSOF" "1" "October 2016" "" ""
.
.SH "NAME"
\fBlsof\fR \- lsof open files
.
.SH "NOME"
\fBlsof\fR \- lsof exibe os files descriptos, ou seja descritores de arquivo, SOCKETS TCP/UDP, etc\.
.
.SH "SYNOPSIS"
\fBlsof\fR [\fB<OPTIONS>\fR] [\fB>\fR \fIout\-file\fR ]
.
.SH "DESCRIÇÃO"
\fBlsof\fR é utiluizado para ver quais programas estão usando os sockets, file descriptors, arquivos abertos etc, assim caso algum arquivo esteja aberto no sistema, poderá ser facilmente encontrado qual programa está usando ele e encerrar esse programa caso necessário, para encerrar programas veja sobre \fBminiman kill\fR
.
.SH "OPÇÕES"
.
.TP
\fB\-i (tcp/udp/etc)\fR
Especifica o tipo do socket tcp/udp/etc
.
.SH "EXEMPLOS"
Exibir os socket tcp:
.
.P
\fB$> lsof \-i tcp\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
