.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LVRESIZE" "1" "December 2016" "" ""
.
.SH "NAME"
\fBlvresize\fR \- model para minhas man pages v1\.0
.
.SH "NOME"
\fBlvresize\fR \- Usado para redimensionar discos Logicos LVM\.
.
.SH "SYNOPSIS"
\fBlvresize\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBlvresize\fR é um programa utilizado para redimencionar, aumentar, diminuir e alterar informações de tamanho de disco\.
.
.SH "OPÇÕES"
.
.TP
\fB\-l\fR
+X%{VG|LV|PVS|FREE|ORIGIN} O tamanho que terá o volume\.
.
.TP
\fB\-L\fR
Tamanho em bytes, use 10MB ou 10240\.
.
.SH "EXEMPLOS"
Extender o volume para 100% do espaço livre\.
.
.P
\fB$> lvresize \-l +100%FREE /dev/volume/logical volume\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
