.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPM" "1" "June 2018" "" ""
.
.SH "NAME"
\fBnpm\fR \- Descrição do programa MarkDown para gerar MiniMan Pages Próprias por Rafael Quirino\.
.
.SH "SYNOPSIS"
\fBnpm\fR [\fBoptions\fR] [\fB\-g\fR \fIlista de pacotes\fR ] \fIpackage\-name\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBnpm\fR NodeJS Package Manager
.
.SH "OPÇÕES"
.
.IP "\(bu" 4
\fBnpm config set prefix "/lib/node\-modeules"\fR: Define o local onde será armazenada
.
.IP "\(bu" 4
\'npm \-g request Instala o modulo request globalmente\.
.
.IP "" 0
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.SH "ARQUIVOS"
\fI/etc/foo\.conf\fR
.
.P
\fI~/\.foorc\fR
.
.SH "ENVIRONMENT"
.
.SH "DIAGNOSTICS"
.
.SH "COMENTARIOS"
.
.SH "BUGS"
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
node(5), npm(1), nodemon(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
