.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET" "1" "April 2017" "" ""
.
.SH "NAME"
\fBpuppet\fR \- puppet usado para orquestrar servidores em ambientes de produção\.
.
.SH "SYNOPSIS"
\fBpuppet\fR [\fBACAO\fR] [\fB\-\-opcoes\fR \fB\-c\fR \fIconfig\-file\fR ] \fIcomando\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBpuppet\fR é um documento escrito para facilitar a crição de documentos a partir de um template\. Com a MARCAÇÃO \fImarkup\fR é possível gerar Man Pages usando o comando \fBronn\fR\. Veja mais em ronn(1)\. Necessita Ruby >= 2\.0 com Mustache para funcionar\.\.
.
.SH "OPÇÕES"
.
.IP "\(bu" 4
\fB\-t\fR: Fazer um teste\.
.
.IP "\(bu" 4
\fB\-\-server\fR \fIhostname\fR: Usa o servidor indicado para conectar\.
.
.IP "\(bu" 4
\fB\-\-environment *AMBIENTE*\fR: Define o ambiente a ser utilizado devel, homol, production
.
.IP "\(bu" 4
\fB\-\-noop\fR: O puppet vai sugerir oque deve mudar sem fazer nada\.
.
.IP "\(bu" 4
\fB\-\-tags=<container>\fR: usado para executar somente um container\.
.
.IP "" 0
.
.SH "EXEMPLOS"
.
.nf

Exibir os cerificados:
.
.fi
.
.P
\fB$> puppet cert \-\-list \-\-all\fR
.
.IP "" 4
.
.nf

Testar conexao com servidor\.com\.br:
.
.fi
.
.IP "" 0
.
.P
\fB$> puppet agent \-\-server servidor\.com\.br \-\-test\fR
.
.IP "" 4
.
.nf

Executar servidor no modo debug:
.
.fi
.
.IP "" 0
.
.P
\fB$> puppet master \-\-no\-daemonize \-debug\fR
.
.IP "" 4
.
.nf

Verificar se o arquivo esta configurado corretamente, e sem erros aparentes:
.
.fi
.
.IP "" 0
.
.P
\fB$> puppet parser validate site\.pp\fR
.
.IP "" 4
.
.nf

Executar o puppet no servidor no\.
`puppetd \-\-server=auto\-gt\.intranet \-\-no\-daemonize \-\-no\-usecacheonfailure \-o \-\-factsync \-\-report \-d`
.
.fi
.
.IP "" 0
.
.SH "ARQUIVOS"
\fI/etc/foo\.conf\fR The system wide configuration file\. See foo(5) for further details\.
.
.P
\fI~/\.foorc\fR Per user configuration file\. See foo(5) for further details\.
.
.SH "ENVIRONMENT"
\fBFOOCONF\fR If non\-null the full pathname for an alternate system wide \fI/etc/foo\.conf\fR\. Overridden by the \fB\-c\fR option\.
.
.SH "DIAGNOSTICS"
Executando testes com o puppet na linha de comando:
.
.P
$> puppet resource package htop ensure=absent
.
.P
$> puppet resource package htop ensure=installed
.
.P
$> puppet resource services apache ensure=started
.
.SH "COMENTARIOS"
Coloque seus comentários aqui\.\.\. <\- Tag para comentários na Man Page, juro, não sai nada\.>
.
.SH "BUGS"
The command name should have been chosen more carefully to reflect its purpose\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
