.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SHOWKEY" "1" "October 2016" "" ""
.
.SH "NAME"
\fBshowkey\fR \- showkeyo para minhas man pages v1\.0
.
.SH "NOME"
\fBshowkey\fR \- showkeyo de arquivo MarkDown para gerar Man Pages por Rafael Quirino\.
.
.SH "SYNOPSIS"
\fBshowkey\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBshowkey\fR exibe o código da tecla digitada\.
.
.SH "OPÇÕES"
.
.TP
\fB\-a\fR
Exibe o caracter em ASCII\.
.
.IP
Crtl+D \-> Sair
.
.SH "EXEMPLOS"
.
.IP "1." 4
Coloque os exemplos aqui:
.
.IP
\'$>showkey \-a\'
.
.IP "" 0
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
tput(5), termcap(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
