.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SQLPLUS" "1" "December 2016" "" ""
.
.SH "NAME"
\fBsqlplus\fR \- sqlplus \- Cliente de SQL Oracle
.
.SH "NOME"
\fBsqlplus\fR \- sqlplus é um aplicativo para conectar no banco de dados oracle e enviar comandos SQL\.
.
.SH "SYNOPSIS"
\fBsqlplus\fR [\fB/ as sysdba\fR] [] \.\.\.
.
.SH "DESCRIÇÃO"
\fBsqlplus\fR é um aplicativo do Oracle usado para executar querys PL/SQL do Oracle\. Com ele é possível executar todas as tarefas de adminsitração do banco de dados Oracle\.
.
.SH "OPÇÕES"
.
.TP
\fB/ as sysdba\fR
Conectar no banco como uusário ADMIN(SYSTEM)
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.P
\fB$> date \'%Y/%m/%d\'\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
