.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TR" "1" "May 2017" "" ""
.
.SH "NAME"
\fBtr\fR \- Tradutor de um caracter para outro
.
.SH "SYNOPSIS"
\fBtr\fR [\fBchar\fR] [\fBchar\fR]
.
.SH "DESCRIÇÃO"
\fBtr\fR é um tradutor de caracteres, de um para um\. Esse e o unico problema, mas util em muitos casos\.
.
.SH "OPÇÕES"
.
.SH "EXEMPLOS"
Apagar quebra de linhas \fB$> cat arquivo | tr \'\en\' \'\e0\'\fR
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
