.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MODEL" "1" "December 2016" "" ""
.
.SH "NAME"
\fBmodel\fR \- modelo para minhas man pages v1\.0
.
.SH "NOME"
\fBmodel\fR \- Modelo de arquivo MarkDown para gerar Man Pages por Rafael Quirino\.
.
.SH "SYNOPSIS"
\fBmodel\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBmodel\fR é um documento escrito para facilitar a crição de documentos a partir de um template\. Com a MARCAÇÃO \fImarkup\fR é possível gerar Man Pages usando o comando \fBronn\fR\. Veja mais em ronn(1)\. Necessita Ruby >= 2\.0 com Mustache para funcionar\.\.
.
.SH "OPÇÕES"
.
.TP
\fB\-b\fR
Do not write "busy" to stdout while processing\.
.
.TP
\fB\-c\fR \fIconfig\-file\fR
Use the alternate system wide \fIconfig\-file\fR instead of \fI/etc/foo\.conf\fR\. This overrides any \fBFOOCONF\fR environment variable\.
.
.TP
\fB\-a\fR
In addition to the baz segments, also parse the blurfl headers\.
.
.TP
\fB\-r\fR
Recursive mode\. Operates as fast as lightning at the expense of a megabyte of virtual memory\.
.
.SH "EXEMPLOS"
Coloque os exemplos aqui:
.
.P
\fB$> date \'%Y/%m/%d\'\fR
.
.SH "ARQUIVOS"
\fI/etc/foo\.conf\fR The system wide configuration file\. See foo(5) for further details\.
.
.P
\fI~/\.foorc\fR Per user configuration file\. See foo(5) for further details\.
.
.SH "ENVIRONMENT"
\fBFOOCONF\fR If non\-null the full pathname for an alternate system wide \fI/etc/foo\.conf\fR\. Overridden by the \fB\-c\fR option\.
.
.SH "DIAGNOSTICS"
The following diagnostics may be issued on stderr:
.
.P
\fBBad magic number\.\fR The input file does not look like an archive file\.
.
.P
\fBOld style baz segments\.\fR \fBfoo\fR can only handle new style baz segments\. COBOL object libraries are not supported in this version\.
.
.SH "COMENTARIOS"
Coloque seus comentários aqui\.\.\. <\- Tag para comentários na Man Page, juro, não sai nada\.>
.
.SH "BUGS"
The command name should have been chosen more carefully to reflect its purpose\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
