.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "VXDISK" "1" "March 2018" "" ""
.
.SH "NAME"
\fBvxdisk\fR \- Descrição do programa MarkDown para gerar MiniMan Pages Próprias por Rafael Quirino\.
.
.SH "SYNOPSIS"
\fBvxdisk\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBvxdisk\fR é um documento escrito para facilitar a crição de documentos a partir de um template\. Com a MARCAÇÃO \fImarkup\fR é possível gerar Man Pages usando o comando \fBronn\fR\. Veja mais em ronn(1)\. Necessita Ruby >= 2\.0 com Mustache para funcionar\.\.
.
.SH "OPÇÕES"
.
.TP
\fB\-i <DISK_NAME>\fR
Quando o disco está com status invalid, ele tira esse erro e poe \fIONLINE\fR
.
.TP
\fB\-C\fR \fIconfig\-file\fR
Use the alternate system wide \fIconfig\-file\fR instead of \fI/etc/foo\.conf\fR\. This overrides any \fBFOOCONF\fR environment variable\.
.
.TP
\fB\-a\fR
In addition to the baz segments, also parse the blurfl headers\.
.
.TP
\fB\-r\fR
Recursive mode\. Operates as fast as lightning at the expense of a megabyte of virtual memory\.
.
.SH "EXEMPLOS"
Obter os dados do MD_3000 (UUID/hostid/disk/group/info/flags/guid/udid,etc)
.
.P
\fB$> vmdisk list md3000_0\'\fR group: name=NARUTO168_DG id=1247647907\.16\.naruto168\-b info: format=cdsdisk,privoffset=256,pubslice=3,privslice=3 flags: online ready private autoconfig autoimport imported pubpaths: block=/dev/vx/dmp/md30000_0s3 char=/dev/vx/rdmp/md30000_0s3 guid: {b31b4574\-1dd1\-11b2\-ae74\-bd96287ddab0} udid: DELL%5FMD3000%5F6002219000BEF44C0000000049D54E69%5F6002219000BEF44C000001F64A439E61
.
.SH "ARQUIVOS"
\fI/etc/foo\.conf\fR The system wide configuration file\. See foo(5) for further details\.
.
.P
\fI~/\.foorc\fR Per user configuration file\. See foo(5) for further details\.
.
.SH "ENVIRONMENT"
\fBFOOCONF\fR If non\-null the full pathname for an alternate system wide \fI/etc/foo\.conf\fR\. Overridden by the \fB\-c\fR option\.
.
.SH "DIAGNOSTICS"
.
.nf

  Para verificar o status do uso do disco, uma forma interessante é:
      `while : ; do iostat ; sleep 2; done`

  Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
  sda               2\.33        44\.77        94\.98    2800966    5941856
  sdb               5\.94        42\.48        26\.55    2657200    1660934
  sdc             133\.79      2185\.01        55\.95  136688223    3500200
  sdd              78\.07      1150\.80       121\.17   71991234    7580175
  sde              78\.52      1162\.68       104\.37   72734119    6528947
  sdf               0\.01         0\.28         0\.91      17289      56632
  sdg               0\.01         0\.05         0\.00       3424          0
  sdh               0\.01         0\.05         0\.00       3246          0
  sdi               0\.01         0\.05         0\.00       3424          0
  dm\-0              8\.76         7\.32        62\.76     458192    3925808
  dm\-1              0\.81         6\.55         3\.35     409970     209368
  dm\-2              0\.79         4\.21         5\.86     263642     366328
  dm\-3              0\.10         3\.62         0\.12     226714       7624
  dm\-4              1\.35        16\.51         8\.57    1032634     536400
  dm\-5              1\.90         6\.00        14\.33     375370     896296
  VxVM32999         5\.11        40\.91        26\.55    2559448    1660934
  VxVM32998       133\.80      2184\.88        55\.06  136680356    3444592
  VxVM32997        78\.10      1150\.68       120\.28   71983452    7524567
  VxVM32996        78\.54      1161\.73       104\.30   72674892    6524697
.
.fi
.
.SH "COMENTARIOS"
Coloque seus comentários aqui\.\.\. <\- Tag para comentários na Man Page, juro, não sai nada\.>
.
.SH "BUGS"
The command name should have been chosen more carefully to reflect its purpose\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
