.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ZPOOL" "1" "December 2016" "" ""
.
.SH "NAME"
\fBzpool\fR \- zpool ZFS Pool utility Manager
.
.SH "NOME"
\fBzpool\fR \- zpool usado para gerenciar pool de discos no ZFS\.
.
.SH "SYNOPSIS"
\fBzpool\fR [\fB<OPTIONS>\fR] [\fBPOOL\fR \fIdevice\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fIZFS\fR é um tipo de filesystem moderno que veio para substituir os sistema tipo LVM no Linux, pois ele simplifica muito além de ser muito mais eficiente e robusto na questão da segurança dos dados\. \fBzpool\fR é uma aplicação utlizada para gerenciar piscina(pool) de discos, com ele é possível criar, excluir, adicionar e fazer toda a manutenção de um pool de arquivos \fBZFS\fR\. Veja mais em zfs(1)\.
.
.SH "OPÇÕES"
.
.TP
\fBattach <POOL> <DEVICE>\fR
Adiciona um disco ao pool de discos\.
.
.TP
\fBstatus \-v <POOL>\fR
Exibe o status da \fBPOOL\fR\.
.
.TP
\fBreplace <POOL> <DEVICE>\fR
Com esse comando é possível trocar o disco usado \fIDEVICE\fR, após isso será refeito o silvering, após o silvering basta executar o comando novamente passando o novo dispositivo que será substituido\.
.
.TP
\fBdetach <POOL> <DEVICE>\fR
Retirar um disco \fIdevice\fR do \fIPOOL\fR
.
.TP
\fBscrub rpool\fR
Faz um scrub do disco, isso faz tipo uma checagem dos CHECKSUMS \fBrecomenda\-se fazer o \fISCRUBING\fR pelo menos uma vez ao mês\.\fR
.
.TP
\fBcreate mypool mirror /dev/da2 /dev/da3\fR
Cria um 2 discos no formato \fImirror\fR
.
.TP
\fBcreate mypool mirror /dev/da2 /dev/da3 mirror /dev/da4 /dev/da5\fR
Cria dois mirrors somados de 2 discos cada\. um mirror (da2,da3) mais outro mirror(da4,da5)\.
.
.TP
\fBcreate mypool raidz2 /dev/ada0p3 /dev/ada1p3 /dev/ada2p3 /dev/ada3p3 /dev/ada4p3 /dev/ada5p3\fR
Cria um RAID Z2 com todos esses discos
.
.TP
\fBclear <POOL>\fR
Limpa erros que por ventura ocorreram no disco\.
.
.TP
\fBcreate healer mirror /dev/ada0 /dev/ada1\fR
Esse comando permite criar um SELF\-HEALER, auto\-cura, isso permite que o próprio sistema faça a checagem dos checksums dos blocks, quando esse não bate ele automaticamente recupera as informações do disco\.
.
.TP
\fBexport <HEALER>\fR
Esse comando permite que o \fIHEALER\fR seja exportado\.
.
.TP
\fBstatus <HEALER>\fR
Exibe o status do \fIHEALER\fR\.
.
.TP
\fBscrub <HEALER>\fR
Faz o scrub do \fIHEALER\fR\.
.
.TP
\fBclear <HEALER>\fR
Faz a limpeza dos erros no \fIHEALER\fR
.
.TP
\fBexport <POOL>\fR
Faz o export da POOL
.
.TP
\fBimport\fR
Exibe os possíveis pools não utilizados e que podem ser importados\.
.
.TP
\fBimport \-o altroot=/mnt mypool\fR
Faz o import do POOL em um diretório alternativo de root
.
.TP
\fBhistory\fR:

.
.TP
\fBupgrade\fR:

.
.TP
\fBiostat\fR
Exibe informaações do tráfego de dados nos dispositivos do pool\.
.
.SH "EXEMPLOS"
Exibir as informações do pool:
.
.P
\fB$> zpool status \-v\fR
.
.SH "ARQUIVOS"
\fI/etc/foo\.conf\fR The system wide configuration file\. See foo(5) for further details\.
.
.P
\fI~/\.foorc\fR Per user configuration file\. See foo(5) for further details\.
.
.SH "ENVIRONMENT"
$ zfs set compression=on mysqlpool $ zfs set dedup=on mysqlpool $ zfs set atime=off mysqlpool
.
.SH "DIAGNOSTICS"
Criei um script para fazer o scrub do ZFS, está na pasta de CDSHELL/script/ZFS
.
.P
\fIDEGRADED\fR
.
.P
Quando um disco entra no modo \fBDEGRADED\fR é possível substitui\-lo com o seguinte comando: \fB$> zpool replace mypool 316502962686821739 ada2p3\fR onde esse numero é o numero que aparece no disco zuado, quando executado zpool status
.
.P
\fB$> zpool status\fR NAME STATE READ WRITE CKSUM mypool DEGRADED 0 0 0 mirror\-0 DEGRADED 0 0 0 ada0p3 ONLINE 0 0 0 316502962686821739 UNAVAIL 0 0 0 was /dev/ada1p3
.
.P
\fIONLINE\fR Significa que o disco está ONLINE, e sem problemas de replicação\.
.
.P
\fIUNAVAIL\fR \fBfoo\fR can only handle new style baz segments\. COBOL object libraries are not supported in this version\.
.
.SH "COMENTARIOS"
Coloque seus comentários aqui\.\.\. <\- Tag para comentários na Man Page, juro, não sai nada\.>
.
.P
Segundo o site prefetch\.net é possível fazer um tunning dos scrubs com os seguintes comandos
.
.P
In particular, the “zfs:zfs_scrub_delay” (I believe) defines the # of seconds to pause a scrub if there’s I/O in the pool\. If you set this to 0, then the scrub will go to town regards of activity on the pool\. For example, I have the following line in my /etc/system file to set this tuneable: set zfs:zfs_scrub_delay = 0x1
.
.SH "BUGS"
The command name should have been chosen more carefully to reflect its purpose\.
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
