.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LSVG" "1" "June 2015" "" ""
.
.SH "NAME"
\fBlsvg\fR \- lsvg para minhas man pages v1\.0
.
.SH "NOME"
\fBlsvg\fR \- lsvg exibe as informações do VG\.
.
.SH "SYNOPSIS"
\fBlsvg\fR [\fB\-bar\fR] [\fB\-c\fR \fIconfig\-file\fR ] \fIfile\fR \.\.\.
.
.SH "DESCRIÇÃO"
\fBlsvg\fR é usado para exibir informações sobre o VG\. No AIX o rootvg é o VG padrão do sistema\.
.
.SH "OPÇÕES"
.
.SH "EXEMPLOS"
.
.SH "ARQUIVOS"
.
.SH "AUTOR"
Rafael Quirino \- \fIquirinobytes (a) gmail com\fR
.
.SH "VEJA SOBRE"
ronn(5), markdown(1), txt2tags(1) Linux Man Page Howto \fIhttp://www\.schweikhardt\.net/man_page_howto\.html\fR
